### ISSUE TITLE
Consider providing the attach.xbe source code.

### ISSUE THREAD

**Issue by TheMuso** [Team-Resurgent/Repackinator#11]
I am wondering whether the source code for attach.xbe could be included in the repo. The original attach.c from rmenhal's drive image utils package is licensed under GPL 2. If the new attach.xbe is a complete rewrite under a different license, and or uses leaked MS code, then I understand if you choose to deny this request.

Thanks in advance.

**Comment by Gunnar-GO** [comment]
It may be an interesting request to look at the source code, but what you imply when people do not follow your request is a rather rude insinuation.

Do you have evidence that it is a reworked development based on the free code? Yes? then present and it will be seen. No? Then you should not make assumptions.

**Comment by GXTX** [comment]
I'm not sure I see the reason to *not* provide the source. It's clear that Cerbios uses a different method of attach (as soon by a simple RE of the default.xbe), and people in the scene *love* to bring up the fact other kernels do not support CCI. Why would one go out of their way to support a proprietary format (ie, how CCI is loaded) if zero support is given?

**Comment by frehov** [comment]
> I'm not sure I see the reason to _not_ provide the source. It's clear that Cerbios uses a different method of attach (as soon by a simple RE of the default.xbe), and people in the scene _love_ to bring up the fact other kernels do not support CCI. Why would one go out of their way to support a proprietary format (ie, how CCI is loaded) if zero support is given?

And you wonder why support is not given if this is how you treat the devs?
Support was offered to stellar, but this was declined by the creator multiple times under the claim that cso would be better as it was a standardized format.

The fact remains that there didnt exist a split cso tool when repackinator and cci was developed.

How about trying to ask nicely instead?
Unless you or the people you're representing are complete douchenozzles, that would be the way to go about it, and not post a passive aggressive BS excuse about support not being given when all you need to do is ask.

**Comment by GXTX** [comment]
> And you wonder why support is not given if this is how you treat the devs?

I'm not sure I'm treating anyone badly, simply asking why the source isn't available.

> Support was offered to stellar, but this was declined by the creator multiple times under the claim that cso would be better as it was a standardized format.
The fact remains that there didnt exist a split cso tool when repackinator and cci was developed.

Wouldn't offering the standard in an open fashion make an even stronger argument against people not supporting it? But this isn't even what I want, or need, just the custom attach changes.

Ftr, I'm not representing anyone lol just trying to add launching CCIs to Lithium for all the Cerbios users. :)

**Comment by EqUiNoX-Labs** [comment]
@GXTX @TheMuso 

https://github.com/Team-Resurgent/Hermes

**Comment by GXTX** [comment]
After I put in the effort to RE it. Aggravating.
https://github.com/Ryzee119/LithiumX/pull/31

**Comment by EqUiNoX-Labs** [comment]
@GXTX i have been on vacation and only attempted to reach out to team Cerbios yesterday.

**Comment by HoRnEyDvL** [comment]
![Screenshot_20230827_131317_Discord](https://github.com/Team-Resurgent/Repackinator/assets/73101201/ecbc9822-6ce3-49a8-8455-209f4abda92c)


I literally sent them a message 24 hours ago once you were told to reach out to the directly.

Maybe should of asked them directly earlier. 🤷 Anyways they sent over the code and we have now put it up. Enjoy

**Comment by EqUiNoX-Labs** [comment]
Just as some background info I did reach out to LoveMhz (Dustin) but never had any replies...

<img width="374" alt="image" src="https://github.com/Team-Resurgent/Repackinator/assets/87106037/508ba281-94b1-4015-86a5-40c771f9cbb6">
