### ISSUE TITLE
MacOS version makes computer very, very slow.

### ISSUE THREAD

**Issue by CaptMoore** [Team-Resurgent/Repackinator#13]
Hello.  On both the 1.1 and 1.1.1 versions, simply running the macOS version of RepackinatorUI causes the computer to start going extremely slow, about a mouse movement every second or so.  This also makes it very hard to even quit the process, an closing the app takes over a minute to even get the correct selections done to kill the app.  

It's so bad that I have been running the Windows version via parallel, as it is useable on the windows platform and completely unusable on my iMac.  

Quitting the terminal restores normal operations and speed to the computer.

For reference, I have a 2017 intel mac with 64gb of ram installed. I am using the latest Ventua macOS release.

**Comment by Natetronn** [comment]
Can you please test the 1.1.5 build and see if it's doing the same thing?

**Comment by HoRnEyDvL** [comment]
Someone on the discord advised the following :)

"On mac, if you need the UI, running repackinator with wine is better, no lag :)"

**Comment by CaptMoore** [comment]
Life has been way to crazy for me to revisit this, but I will test if I can ever get things calmed down at home. Sorry for the delay.

**Comment by Casuallynoted** [comment]
Sadly I'm having the same issue. Maybe some kind of memory leak?

**Comment by Casuallynoted** [comment]
Looks like it's hammering the GPU.

<img width="956" alt="Screenshot 2023-01-15 at 3 05 44 PM" src="https://user-images.githubusercontent.com/6272557/212564365-4ab64ee3-1efe-446a-b07d-81d5a8b0d5a6.png">

**Comment by HoRnEyDvL** [comment]
Latest Version Should address this issue.

Please retest & advise,  Thanks

**Comment by CaptMoore** [comment]
I was able to try it tonight, it isn't slow anymore.  I am having another issue with the text being so small it is unusable, but I will post that in another issue.
