### ISSUE TITLE
Feature Request: Add external extractor

### ISSUE THREAD

**Issue by rizaumami** [Team-Resurgent/Repackinator#16]
Trimmed, slimmed (or whatever it's named) XISO probably has already been planned.
Am not a conservationist, so using 7 GB space for 300 MB game is not for me.
Meanwhile, perhaps we can have options to:
- using external extractor (e.g. `extract-xiso`), or
- just generate `attach.xbe` and `default.tbn`, so user can "extract" xiso by themself using another extractor.

**Comment by rizaumami** [comment]
Never mind, seems like "Attach Update" do the magic I was asking.

**Comment by Natetronn** [comment]
As you can see from the more recent builds, Scrub, Truncate and Compression is in the works.

**Comment by rizaumami** [comment]
I've tried v1.1.7, Compress, Trim Scrub, and Traverse Input Subdir's menus are there but the functionality aren't.
I'll keep this request open until they're fully implemented.

**Comment by Natetronn** [comment]
Try only Trim and Scrub this time, as Compress produces a cci image (Cerbios Compressed Image) that will require a yet to be released version of Cerb.

**Comment by rizaumami** [comment]
Trim Scrub work, but produced quite larger ISO compared to `extract-xiso`, e.g 3,6 GB vs 1,4 GB with SoulCalibur II.
Not interested in CCI as it will lock me to Cerbios.
Think you guys are on the right track, so I shall close this issue and wait.
