### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by rizaumami** [Team-Resurgent/Repackinator#17]
Repackinator: RepackinatorUI-linux-x64 v1.1.1
OS: Linux sid 6.0.0-5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.10-2 (2022-12-01) x86_64 GNU/Linux
Redump ISO: Jade Empire (USA, Europe) (En,Es,It), CRC32: 9CD53B00

Repackinator eat all of the system's RAM until the operating system automatically logged out.
`default.tbn` and `default.xbe` was successfully created, but not the xiso.

![System Monitor](https://user-images.githubusercontent.com/11420518/205431105-ac6fd6d4-4027-4420-ae58-c22b5f042662.png)

**Comment by Natetronn** [comment]
Try recent update (v1.1.5) and let us know if that's working better for you.

**Comment by rizaumami** [comment]
Fixed in v1.1.7.
