### ISSUE TITLE
An option to verify that CCIs in the output folder are correct

### ISSUE THREAD

**Issue by Casuallynoted** [Team-Resurgent/Repackinator#32]
One thing I've noticed is that while I've been converting crazy amounts of games over to CCI (I'm sending them to a NAS so it's writing over the net), every once in a while if internet wonkiness happens, it'll output a very small and incomplete file. However, when doing the Scan Output option, so long as it sees the file, Repackinator is usually happy to keep moving. Is there a way to maybe have the option to run the files through a checksum just to make sure they're totally ok? That way I can catch instances where that's happened.

**Comment by Dempsey86** [comment]
You can calculate all the sha256 hashes in a folder and the sub folders of it in batch with a program called multihasher. Then you can compare them with the ones in this list: https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vSewa5ynfmFC6Dg9FeF9nBF511dGgHc6VwtmR5AH3yyba-bqXO2OAvR-_xxPSLk84xCiM8LxntTYzHX/pubhtml?gid=0&single=true
