### ISSUE TITLE
Trrntzip 7z files unable to process.

### ISSUE THREAD

**Issue by projectzero** [Team-Resurgent/Repackinator#37]
OS: Windows 10 Home 64bit
Repackinator v1.2.9

7z files created by 7-Zip can be extracted/processed as expected. 7z files created by Trrntzip (https://romvault.com/trrntzip/) generates an error. 

![7zerror](https://user-images.githubusercontent.com/3341925/223883008-ebc04bf8-1536-41c7-9845-6b62daf08450.PNG)

**Comment by frehov** [comment]
Hi, this seems like it's not a Repackinator issue, we suggest you open an issue with the [SharpCompress](https://github.com/adamhathcock/sharpcompress/issues) project instead.

If it's not supported by sharpcompress, then it would first need to be supported there before we can update Repackinator with the updated library.

**Comment by HoRnEyDvL** [comment]
Pending update from sharp compress
