### ISSUE TITLE
Game name is invalid 

### ISSUE THREAD

**Issue by Kog1984** [Team-Resurgent/Repackinator#39]
Doesn’t like comma in name

Red Star, The
Ultimate Selection, The

Just helping in case anyone else has same issue

**Comment by Kog1984** [comment]
It’s in this file why reported it RepackList.json

**Comment by Dempsey86** [comment]
I see, it's in the AltRepackList.json. thanks for reporting, it was not really clear at first. The alt list is not tested, its only added to make it simple for the people to add games to the RepackList.json

**Comment by HoRnEyDvL** [comment]
Both Titles updated in AltRepackList.json

Thanks :)
