### ISSUE TITLE
Won't run on VirtualBox: Could not create GL context: A directory service error has occurred.

### ISSUE THREAD

**Issue by rizaumami** [Team-Resurgent/Repackinator#4]
Won't run on Windows 10 LTSC 2021 VirtualBox guest.
```
Veldrid.VeldridException: Unable to create OpenGL Context: "Could not create GL context: A directory service error has occurred.
". This may indicate that the system does not support the requested OpenGL profile, version, or Swapchain format.
   at Veldrid.StartupUtilities.VeldridStartup.CreateDefaultOpenGLGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, GraphicsBackend backend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at RepackinatorUI.Application.Run()
   at Program.<Main>$(String[] args)
```

**Comment by Natetronn** [comment]
Perhaps in the meantime we can side step, what is your host?

**Comment by rizaumami** [comment]
> Perhaps in the meantime we can side step, what is your host?

Debian Sid 64 bit.

> If on Linux, you might try using WINE instead of VirtualBox. You may need to set Windows Version to Windows 10 using winecfg.

I'm hesitant to install wine because it will bring plethora of dependencies with it.  
`wine` packaged as AppImage probably will solved that.

> You might try installing Guest Additions (extension pack), if you haven't already (although I'm not sure the OpenGL support it provides is sufficient.)

I did. 

> Also, you might try the suggestion here: https://superuser.com/a/1671809 and here: https://forums.virtualbox.org/viewtopic.php?t=101304#p491844

Unfortunately the [Mesa3D](https://fdossena.com/?p=mesa/index.frag) link is unreachable.

> You might try a different graphics setting: https://superuser.com/a/1403131
> 
> @ Devs, looks like for Verdrid, OpenGL 3.0 is required: https://github.com/mellinoe/veldrid-docs/blob/master/articles/implementation/opengl.md - Also, I ran into Veldrid errors when trying to compile for Linux, I think I've solved that issue by creating a symlink as shown [here](https://github.com/mellinoe/veldrid/issues/143#issuecomment-446096640), however.

Yeah, I think the problem is OpenGL support by the VirtualBox.  
Thanx for the comprehensive response.

**Comment by Natetronn** [comment]
We're working on a Native Linux version as we speak.

**Comment by rizaumami** [comment]
> We're working on a Native Linux version as we speak. And I don't blame you for not wanting to add WINE.

This is a good news 👍🏽

**Comment by Natetronn** [comment]
Linux version is live:

https://github.com/Team-Resurgent/Repackinator/releases
