### ISSUE TITLE
Decompress CCI Images back to ISO

### ISSUE THREAD

**Issue by jeremysgates** [Team-Resurgent/Repackinator#41]
I didn't see this option in the context menu or documentation.  Is it possible to decompress a .CCI image back to .ISO format?  I would like to store and use my games in .CCI format, would like the ability to decompress them back to ISO if needed in the future.

**Comment by zappepappe** [comment]
Depends on what you mean with .ISO. Repackinator can go from Redump style image>Full game-partition image>Scrubbed image>Trimmed-scrubbed image, but you can't go backwards. CCI and ISO however goes both ways.

**Comment by HoRnEyDvL** [comment]
Closed due to no response.  Please reopen new ticket if required

Thanks
