### ISSUE TITLE
[Feature request] Recreate Redump-matching isos with Repackinator

### ISSUE THREAD

**Issue by awsms** [Team-Resurgent/Repackinator#45]
Would it be possible to recreate an .iso that matches the checksums of redump, after scrubbing a redump iso?

**Comment by awsms** [comment]
I know that NGC & Wii redump-verified isos can be unscrubbed with NKit after scrubbing (and they will rematch the original iso), so maybe it'd be possible for Xbox games too?
If this is definitely not achievable with Repackinator, I'd love to hear some alternative software recommendations. This would be a game changer for all the Xbox isos data hoarders out there!

**Comment by zappepappe** [comment]
The difference is that Xbox uses random padding. Unless you store all the padding as extra files you won't be able to re-create to the original. And at that point you might as well just store the entire file.
