### ISSUE TITLE
MacOS  Text is so tiny it is unusable.

### ISSUE THREAD

**Issue by CaptMoore** [Team-Resurgent/Repackinator#49]
I tried to use this today, but the text displayed is the UI is so small I can't use it.  I have a 27" 2017 intel mac in the default resolution (5k screen) and for some reason the text is so small I can't use it.  

I didn't see any options or settings to increase the text size in the app, although I could have missed it for sure.

Any ideas?  I fully admit is could be user error.

**Comment by CaptMoore** [comment]
Link to a screen shot:  (I hope this works....)
https://www.icloud.com/iclouddrive/05djuzsvWgusretJugb0jISbA#Screenshot_2023-08-28_at_1.19.26_AM

**Comment by HoRnEyDvL** [comment]
Can you please latest build. That should hopefully resolved the issue.

Thanks

**Comment by CaptMoore** [comment]
It appeared to work, I can't test it now but the GUI in normal size now.  Thank you.

**Comment by HoRnEyDvL** [comment]
Thanks for your feedback much appreciated :)
