### ISSUE TITLE
Closing the window doesn't end the process

### ISSUE THREAD

**Issue by dracc** [Team-Resurgent/Repackinator#6]
Starting RepackinatorUI through bash and closing using the X button doesn't give back control of the terminal window.
For some reason, the process doesn't stop.

**Comment by Natetronn** [comment]
@dracc which OS are running it on? Was this the Linux specific version?

**Comment by dracc** [comment]
Sorry for leaving out such basic information!
Yes, my testing was done under Debian Linux, a build shared by Haguero.

**Comment by Natetronn** [comment]
Please give build 1.1.7 a try and let us know how it goes for you.

**Comment by HoRnEyDvL** [comment]
Closed as no feedback received. Should be now fixed if still having issues please reopen ticket.
