### ISSUE TITLE
(question) Scrub vs TrimmedScrub vs XISO

### ISSUE THREAD

**Issue by sekelje** [Team-Resurgent/Repackinator#63]
Hi,

As the title, says, some clarification needed between those formats.
I understand that Scrub replaces padding with zeros while TrimmedScrub removes unused data at the end of data partition which is similar to XISO. What confuses me is that TrimmedScrub actually produces images that are substantially larger than images produced with XISO for most games. Does TrimmedScrub preserve partitions and sectors? Will it break games that rely on sector checks (such as Toca 3)? Or should Scrub only be used for maximum compatibility?

Thanks

**Comment by HoRnEyDvL** [comment]
Please refer to reply from Incursion64 :)
https://github.com/Team-Resurgent/Repackinator/issues/54

**Comment by sekelje** [comment]
Thanks for your response, I have read #54 
Unfortunately it doesn't sound right. Incursion64 says that selecting Trim-Scrub replaces padding with 0's which adds to my confusion because Trim-Scrub actually removes unused data which is in line with my testing. Trim-Scrub images are smaller than Scrub-only images.

So, to recap:
1. Repackinator always removes video partition
2. Unscrubbed and Scrubbed images are the same size, but Scrubbed compresses better because padding is replaced with 0's
3. TrimmedScrub removes unused data at the end of data partition
4. XISO actually rebuilds images

Now, I don't want to sound rude or annoying or to offend someone, but my initial question is still not answered.
Maybe it can't be answered, but does TrimmedScrub break some games?
Reason I ask is because for i.e. trimming redump gamecube/wii images is known to break some games, but only scrubbing is considered to be safe (although pointless nowadays since the introduction of RVZ format)

Thanks
