### ISSUE TITLE
Can't rip any game you want. Please fix this. There is legit no reason why it should be an issue. Thank you!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by MidnightPodcastGaming** [Team-Resurgent/Repackinator#71]
What the title says.
I go to rip an ISO that I've got, to CCI, and it says game not found. It isn't found on the list. Some are found, but not the right region. Mate, can you just let us rip whatever the heck we want? Why are we tied to a list for? If I was your manager, I would NEVER allow this software to be released like that. Sorry for being so blunt, but it's sheer lack of common sense like this that really fires me up. I'm off to stare at my 80 games in a folder that I can't rip using your software. And saddest part is, there is no other CCI converter out there. Yours is the only one, with conditions. You guys are known for your awesome work, so this is extremely disappointing to witness. I tried man. I even tried to turn the list off and bypass the list check. You just can't do it. Hire a quality control lad at your team. To prevent stuff like this in the future. Or hire me. I come cheap. Thank you very much. Back to not being able to rip games for no actual reason at all using your software. Have a lovely week!!!!!!!!!!!!!!!!!

**Comment by MidnightPodcastGaming** [comment]
Another issue now. I decided to be F'd in the ass by your list. Just is what it is. But now, I can't even rip your own games and regions that are on the list. A lot of games rip in two CCI files, EVEN when I set the program to NOT split the files at all. WHAT ON EARTH MAN!!!!!!!!!!!!!!!!!!!! What next, want to blue screen our computers every time we enter the software. Do that next!!!!!!!!!!!!!!!!

**Comment by frehov** [comment]
Closing issue due to the inflammatory accusations.

To be "blunt", as you put it, If you don't like the software provided, make your own version that does what you need it to.

Or "simply" extract the default.xbe and get the necessary info and checksums of your ISOs and make your own list to process those 80 games.

If you fail to see why a curated official list has been made, go pound sand!

**Comment by MidnightPodcastGaming** [comment]
So you're going to be immature? Okay then. To the second issue at hand then, the files breaking into parts when the box is ticked to never break files into two. Splitting ISOs is turned off. It still splits ISOs and CCIs into two. Do you plan on fixing that at least? Or you don't give a crap about fixing that part of your software either? Great group!!!!!!!!!!! You really strive to deliver for your people. Great work.

**Comment by MidnightPodcastGaming** [comment]
So you're going to be immature? Okay then. To the second issue at hand then, the files breaking into parts when the box is ticked to never break files into two. Splitting ISOs is turned off. It still splits ISOs and CCIs into two. Do you plan on fixing that at least? Or you don't give a crap about fixing that part of your software either? Great group!!!!!!!!!!! You really strive to deliver for your people. Great work.


 

Sent: Sunday, June 30, 2024 at 6:24 PM

**Comment by frehov** [comment]
If you feel this angry and can't restrain yourself from hurling abuse and accusations, please consider  stepping away and touching grass for a moment.

I'm not the primary developer of this, but I'm authorized to manage and respond to issues related to our teams repositories.

You're welcome to contribute a fix to the issue instead of hurling abuse.
Did you even try going into the xbox-scene discord to try to resolve your issue before coming here?

You haven't even explained your use-case for needing the files to not split. If you're going to be using them ON the xbox, they have to split due to file system limitations.

**Comment by MidnightPodcastGaming** [comment]
When on earth did I abuse anybody? What are you talking about?

Mate, I told you, I was crystal clear, you cannot do singular CCIs for quite a lot of games. For games that are 1 to 3 GB yeah, for bigger games it breaks them up into CCI 1 and CCI 2. You cannot start the game off of two CCIs. Just black screens and you have to restart the XBOX.

Only one CCI file can start the game. Can't have two. I set the option to NOT SPLIT ISO, which also means CCI, same option would apply there also, and it still breaks them into two. So mate, just because nobody else has bothered to report it doesn't mean it's not an issue. It's there. It happens. And it should seriously be addressed.

Same with not being able to convert any game to CCI. Why on earth not? Why does there need to be a list? I don't understand the reason for it. Just let every game convert to CCI. If there are "compatibility issues" with quite a number of them, let US compile that list of non-working ones, don't compile your own because there will be a tremendous amount that you didn't catch and therefore cannot be tested on our end at all. 

 
 

Sent: Sunday, June 30, 2024 at 11:12 PM

**Comment by frehov** [comment]
It seems you don't understand why there is a need to split.

The filesystem on the xbox cannot take files larger than 4GB, if a CCI would end up larger than this, it absolutely is necessary to split the file.

The files are bundled with the attach.xbe as default.xbe to launch the games under a supported/patched bios.

As to the list, this is a curated version containing all ntsc titles, pal exclusives and japan exclusives.
The list is curated (and tested) with checksums for ISOs to ensure that there is no issues converting them so we can avoid user errors and not get blamed for them.

Any other title you want to process, you have to yourself put in the effort to obtain the necessary info for processing them and adding them to the json.

**Comment by MidnightPodcastGaming** [comment]
That's my point, I cannot do that using your software, and over 4GB CAN be copied as an ISO or whatever format onto a HDD with Cerbios. It is legit 100000000000000% doable. I've seen other CCIs that are 5+ GB, they were downloaded CCI ready, didn't need to do them myself. You cannot copy onto a USB more than 4GB, that is correct, but you can FTP no matter the GB size of the image. And jeez louise, you literally have an option saying DO NOT SPLIT ISOs, if what you're saying is the case, why would there even be an option to not split them!!!! May I repeat, the 2 CCIs per game DOES NOT work. It renders the operation useless. And you're worried about being blamed for errors? What about breaking two CCI files for a game and then 100% not being able to run on any XBOX?

 
 

Sent: Sunday, June 30, 2024 at 11:54 PM
