### ISSUE TITLE
Add NoSplit to command line options

### ISSUE THREAD

**Issue by eltanno** [Team-Resurgent/Repackinator#76]
Hi, I have just started using the tool. Its great, thanks for making it. 

I see in the latest codebase you have the flag for creating NoSplit .iso files from the gui, but its set to always be off when using the command line. I am stuck using this on Linux at the moment, but want this functionality. Would it be possible to add a build flag on the command line to use the NoSplit option please? 

I could have a go at making a PR for it, but am not sure how to build the project. If you have some build instructions maybe I could get this done.

Thanks again
Jim

**Comment by eltanno** [comment]
I forked, and made a PR in my local here. I think this is all it needs. I have not built, as i am not sure how to build a C# project. I hope this is helpful. 

https://github.com/eltanno/Repackinator/pull/1/files

**Comment by eltanno** [comment]
I got as far as installing dotnet7.0 in linux, and running the ./build.sh comamnd. But it went bang with what I am assuming is some missing stuff from me, like borked configs or missing dependancies. 

```
jim@DESKTOP-HIT52OS:~/projects/Repackinator/Repackinator$ ./build.sh
                                                                                                                                                                                                                                        
Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.119

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
```
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Restored /home/jim/projects/Repackinator/Repackinator.Localization/Repackinator.Localization.csproj (in 112 ms).
  Restored /home/jim/projects/Repackinator/Resurgent.UtilityBelt.Library/Resurgent.UtilityBelt.Library.csproj (in 3.12 sec).
  Restored /home/jim/projects/Repackinator/Repackinator/Repackinator.csproj (in 17.29 sec).
MSBuild version 17.4.8+6918b863a for .NET
  Repackinator.Localization -> /home/jim/projects/Repackinator/Repackinator.Localization/bin/x64/Release/net7.0/Repackinator.Localization.dll
  Resurgent.UtilityBelt.Library -> /home/jim/projects/Repackinator/Resurgent.UtilityBelt.Library/bin/x64/Release/net7.0/Resurgent.UtilityBelt.Library.dll
/usr/lib/dotnet/sdk/7.0.119/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(580,5): warning NETSDK1074: The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server). [/home/jim/projects/Repackinator/Repackinator/Repackinator.csproj]
  Repackinator -> /home/jim/projects/Repackinator/Repackinator/bin/x64/Release/net7.0/win-x64/repackinator.dll
  Repackinator -> /home/jim/projects/Repackinator/Repackinator/bin/x64/Release/net7.0/win-x64/publish/
MSBuild version 17.4.8+6918b863a for .NET
/usr/lib/dotnet/sdk/7.0.119/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file '/home/jim/projects/Repackinator/Repackinator/obj/project.assets.json' doesn't have a tar
get for 'net7.0/linux-x64'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project. You may also need to include 'linux-x64' in your project's RuntimeIdentifiers. [/home/jim/projects/Repackinator/Repackinator/Repackinator.csproj]
MSBuild version 17.4.8+6918b863a for .NET
/usr/lib/dotnet/sdk/7.0.119/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file '/home/jim/projects/Repackinator/Repackinator/obj/project.assets.json' doesn't have a tar
get for 'net7.0/osx-x64'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project. You may also need to include 'osx-x64' in your project's RuntimeIdentifiers. [/home/jim/projects/Repackinator/Repackinator/Repackinator.csproj]
```

**Comment by EqUiNoX-Labs** [comment]
Added for convert as well as encoding
