### ISSUE TITLE
v1.5 Display issues

### ISSUE THREAD

**Issue by mrdude2478** [Team-Resurgent/Repackinator#78]
When using v1.4.4 the app works fine and displays the bar with the buttons at the bottom of the screen (save game data, save selected, etc)

On v1.5.0 (Latest pre), these buttons are missing from the bottom of the screen and I can't resize the app to show them.

**Comment by Dempsey86** [comment]
This is fixed in Repackinator V1.5.1 (latest pre release)

**Comment by mrdude2478** [comment]
Thank you for fixing.
